import {C, h} from './homeStyles.jsx'

export const d = {
  root:        { display:"flex", height:"100vh", width:"100vw", background:C.bg, fontFamily:"'Sora', sans-serif", color:C.text, overflow:"hidden" },
  sidebar:     { width:224, background:C.sidebar, borderRight:`1px solid ${C.sidebarBorder}`, display:"flex", flexDirection:"column", padding:"20px 0", flexShrink:0 },
  logo:        { display:"flex", alignItems:"center", gap:10, padding:"0 20px 20px", borderBottom:`1px solid ${C.sidebarBorder}` },
  logoMark:    { width:34, height:34, borderRadius:10, background:`linear-gradient(135deg,#1565a8,#2980c4)`, display:"flex", alignItems:"center", justifyContent:"center", color:"#fff", flexShrink:0 },
  logoTitle:   { fontSize:14, fontWeight:700, color:C.text },
  logoSub:     { fontSize:9, color:C.textMuted, letterSpacing:1 },
  hospitalBadge:{ margin:"14px 14px 6px", padding:"10px 12px", background:C.bgDeep, borderRadius:10, border:`1px solid ${C.border}` },
  nav:         { padding:"8px 12px", flex:1, display:"flex", flexDirection:"column", gap:2 },
  navBtn:      { display:"flex", alignItems:"center", gap:10, padding:"9px 12px", borderRadius:9, border:"none", background:"transparent", color:C.textMuted, cursor:"pointer", fontSize:12, textAlign:"left", transition:"all 0.18s", width:"100%" },
  navActive:   { background:C.blueDim, color:C.blue, borderLeft:`2px solid ${C.blue}` },
  navIcon:     { fontSize:14, width:16, textAlign:"center" },
  badge:       { marginLeft:"auto", fontSize:9, fontWeight:700, padding:"2px 6px", borderRadius:8, background:C.redDim, color:C.red },
  sidebarFooter:{ padding:"14px 20px", borderTop:`1px solid ${C.sidebarBorder}` },
  logoutBtn:   { marginTop:8, fontSize:10, padding:"5px 8px", border:`1px solid ${C.border}`, background:"transparent", cursor:"pointer", color:C.textMuted, borderRadius:6, width:"100%", fontFamily:"'DM Mono', monospace" },
  main:        { flex:1, display:"flex", flexDirection:"column", overflow:"hidden" },
  topbar:      { padding:"14px 24px", borderBottom:`1px solid ${C.border}`, display:"flex", justifyContent:"space-between", alignItems:"center", background:C.bgCard, flexShrink:0 },
  pageTitle:   { fontSize:16, fontWeight:700, color:C.text },
  searchBox:   { display:"flex", alignItems:"center", gap:8, padding:"7px 12px", background:C.bgDeep, border:`1px solid ${C.border}`, borderRadius:10 },
  searchInput: { background:"transparent", border:"none", outline:"none", color:C.text, fontSize:12, width:160, fontFamily:"'DM Mono', monospace" },
  avatarBtn:   { width:32, height:32, borderRadius:"50%", background:`linear-gradient(135deg,#1565a8,#2980c4)`, display:"flex", alignItems:"center", justifyContent:"center", fontSize:10, fontWeight:700, color:"#fff" },
  content:     { flex:1, overflowY:"auto", padding:24 },
  dashGrid:    { display:"grid", gridTemplateColumns:"repeat(4,1fr)", gap:14 },
  kpiCard:     { background:C.bgCard, border:`1px solid ${C.border}`, borderRadius:14, padding:18 },
  card:        { background:C.bgCard, border:`1px solid ${C.border}`, borderRadius:14, padding:18 },
  cardHeader:  { display:"flex", justifyContent:"space-between", alignItems:"center" },
  cardTitle:   { fontSize:11, color:C.textMuted, letterSpacing:1, textTransform:"uppercase" },
  diagCard:    { background:C.bgDeep, borderRadius:12, padding:"14px 12px", border:`1px solid ${C.border}`, textAlign:"center" },
  protocolRow: { display:"flex", alignItems:"center", gap:10, padding:"8px 10px", background:C.bgDeep, borderRadius:10 },
  filterBar:   { display:"flex", alignItems:"center", gap:10, flexWrap:"wrap", padding:"10px 14px", background:C.bgCard, borderRadius:12, border:`1px solid ${C.border}` },
  filterBtn:   { fontSize:10, padding:"5px 10px", borderRadius:8, border:`1px solid ${C.border}`, background:"transparent", color:C.textMuted, cursor:"pointer", transition:"all 0.15s" },
  tableWrap:   { background:C.bgCard, border:`1px solid ${C.border}`, borderRadius:14, overflow:"hidden" },
  table:       { width:"100%", borderCollapse:"collapse" },
  th:          { padding:"10px 14px", textAlign:"left", fontSize:9, color:C.textDimmer, letterSpacing:1, textTransform:"uppercase", borderBottom:`1px solid ${C.border}`, background:C.bgDeep },
  tr:          { borderBottom:`1px solid ${C.bgRow}`, cursor:"pointer", transition:"background 0.15s" },
  td:          { padding:"11px 14px", fontSize:12, color:C.textSub },
  viewBtn:     { fontSize:10, color:C.blue, background:"transparent", border:`1px solid ${C.border}`, borderRadius:6, padding:"4px 8px", cursor:"pointer" },
  toast:       { position:"fixed", bottom:24, right:24, padding:"12px 20px", borderRadius:12, fontSize:12, fontWeight:600, color:"#fff", zIndex:200, display:"flex", alignItems:"center", gap:8, boxShadow:"0 8px 32px rgba(14,40,100,0.15)" },
};