export const C = {
  bg:          "#f0f4ff",
  bgCard:      "#ffffff",
  bgDeep:      "#f5f8ff",
  bgRow:       "#eef2fc",
  border:      "#d4ddf5",
  borderBright:"#b8c8ef",
  blue:        "#0e7fc2",
  blueDim:     "rgba(14,127,194,0.10)",
  blueFaint:   "rgba(14,127,194,0.05)",
  green:       "#0a9e73",
  greenDim:    "rgba(10,158,115,0.10)",
  red:         "#d63355",
  redDim:      "rgba(214,51,85,0.10)",
  orange:      "#d9800a",
  orangeDim:   "rgba(217,128,10,0.10)",
  text:        "#1a2540",
  textSub:     "#4a5878",
  textMuted:   "#8494b8",
  textDim:     "#9daacf",
  textDimmer:  "#b8c4dc",
  sidebar:     "#f8faff",
  sidebarBorder:"#e4ecfa",
};

export const h = {
  root:     { minHeight:"100vh", background:C.bg, display:"flex", alignItems:"center", justifyContent:"center", fontFamily:"'DM Mono', monospace", position:"relative" },
  grid:     { position:"absolute", inset:0, backgroundImage:`linear-gradient(${C.border} 1px,transparent 1px),linear-gradient(90deg,${C.border} 1px,transparent 1px)`, backgroundSize:"36px 36px", opacity:0.5, pointerEvents:"none" },
  card:     { position:"relative", zIndex:1, background:C.bgCard, border:`1px solid ${C.borderBright}`, borderRadius:20, padding:"36px 36px 28px", width:"100%", maxWidth:480, display:"flex", flexDirection:"column", gap:20, boxShadow:"0 4px 32px rgba(14,40,100,0.08)" },
  logoRow:  { display:"flex", alignItems:"center", gap:12 },
  logoMark: { width:40, height:40, borderRadius:12, background:`linear-gradient(135deg,#1565a8,#2980c4)`, display:"flex", alignItems:"center", justifyContent:"center", flexShrink:0 },
  brandName:{ fontSize:15, fontWeight:700, color:C.text },
  brandSub: { fontSize:9, color:C.textMuted, letterSpacing:1 },
  rule:     { height:1, background:C.border },
  titleBlock:{ display:"flex", flexDirection:"column", gap:6 },
  title:    { fontSize:22, fontWeight:700, color:C.text, letterSpacing:-0.5 },
  subtitle: { fontSize:12, color:C.textMuted },
  roleRow:  { display:"grid", gridTemplateColumns:"1fr 1fr", gap:12 },
  roleCard: { display:"flex", flexDirection:"column", alignItems:"flex-start", gap:4, padding:"18px 16px", border:`1px solid ${C.border}`, borderRadius:14, background:C.bgDeep, cursor:"pointer", textAlign:"left", transition:"all 0.15s", fontFamily:"'DM Mono', monospace", position:"relative" },
  roleIcon: { fontSize:24, marginBottom:4 },
  roleLabel:{ fontSize:14, fontWeight:700, color:C.text },
  roleSub:  { fontSize:10, color:C.textMuted, lineHeight:1.5 },
  roleArrow:{ position:"absolute", top:16, right:16, fontSize:14, color:C.blue },
  backBtn:  { fontSize:10, padding:"4px 10px", border:`1px solid ${C.border}`, background:"transparent", cursor:"pointer", color:C.textMuted, borderRadius:6, marginBottom:12, fontFamily:"'DM Mono', monospace" },
  roleSelectedBadge:{ display:"flex", alignItems:"center", gap:8, padding:"8px 12px", background:C.blueDim, borderRadius:10, border:`1px solid ${C.blue}30` },
  roleBadgeIcon:{ fontSize:16 },
  roleBadgeText:{ fontSize:11, color:C.blue, fontWeight:700 },
  searchField:{ border:`1px solid`, borderRadius:10, padding:"10px 14px", transition:"border-color 0.15s", background:C.bgDeep },
  searchInput:{ width:"100%", border:"none", outline:"none", fontSize:13, fontFamily:"'DM Mono', monospace", color:C.text, background:"transparent" },
  dropdown: { position:"absolute", top:"100%", left:0, right:0, background:C.bgCard, border:`1px solid ${C.border}`, borderTop:"none", borderRadius:"0 0 12px 12px", zIndex:50, maxHeight:240, overflowY:"auto", boxShadow:"0 4px 16px rgba(14,40,100,0.08)" },
  dropItem: { display:"flex", alignItems:"center", gap:10, padding:"10px 14px", width:"100%", border:"none", cursor:"pointer", textAlign:"left", fontFamily:"'DM Mono', monospace", borderBottom:`1px solid ${C.border}` },
  dropAvatar:{ width:28, height:28, borderRadius:8, background:C.blueDim, color:C.blue, display:"flex", alignItems:"center", justifyContent:"center", fontSize:10, fontWeight:700, flexShrink:0 },
  dropName: { fontSize:12, fontWeight:700, color:C.text },
  dropMeta: { fontSize:10, color:C.textMuted },
  dropBadge:{ fontSize:8, padding:"2px 6px", border:`1px solid ${C.border}`, color:C.textMuted, borderRadius:4, letterSpacing:1 },
  selectedBox:{ border:`1px solid ${C.blue}50`, borderRadius:12, padding:"16px 16px 14px", display:"flex", flexDirection:"column", gap:6, background:C.blueFaint, marginTop:12 },
  selectedLabel:{ fontSize:8, color:C.blue, letterSpacing:2 },
  selectedName:{ fontSize:18, fontWeight:700, color:C.text },
  selectedMeta:{ fontSize:11, color:C.textMuted },
  proceedBtn:{ marginTop:8, background:`linear-gradient(135deg,#1565a8,#2980c4)`, color:"#fff", border:"none", borderRadius:9, padding:"11px 16px", fontSize:12, fontFamily:"'DM Mono', monospace", cursor:"pointer", fontWeight:700, letterSpacing:1, alignSelf:"flex-start" },
  quickWrap:{ borderTop:`1px solid ${C.border}`, paddingTop:16, marginTop:4 },
  quickLabel:{ fontSize:8, color:C.textDimmer, letterSpacing:2, textAlign:"center", marginBottom:12 },
  quickRow: { display:"grid", gridTemplateColumns:"repeat(3,1fr)", gap:8 },
  quickBtn: { border:`1px solid ${C.border}`, borderRadius:10, padding:"10px 6px", background:C.bgDeep, cursor:"pointer", fontFamily:"'DM Mono', monospace", textAlign:"center", transition:"border-color 0.15s" },
  quickName:{ fontSize:11, fontWeight:700, color:C.text },
  quickSub: { fontSize:9, color:C.textMuted, marginTop:2 },
  quickStatus:{ fontSize:8, letterSpacing:1, marginTop:4 },
};